#_production
website:
  reader-mode: true
  title: ""
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel."
  site-url: https://theupsidedownblog.netlify.app
  favicon: /_img/round_logo2.png
  google-analytics: "G-V3QQ28RRMM"
  navbar: 
    pinned: false
    collapse: true
    logo: /_img/tud_logo2.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Information"
        menu: 
          - text: "About"
            href: about.qmd
          - text: "Creator"
            href: https://ocardec.netlify.app
            target: _blank
      - text: "References"
        href: references/referdx.qmd
    right:
      - text: "Español"
        href: index-es.qmd
      - text: "English"
        href: index.qmd
      - icon: envelope-at
        text: Email
        href: "mailto:admin@theupsidedownblog.com"  

  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      <span class="faux-block">&#169; Copyright 2024 Cardec Solutions</span>
    center: |
      <span class="faux-block">Created in&nbsp;<a href="https://quarto.org" target="_blank"><img src="/_img/quarto.png" width="70"></a></span>
    right: |
      <span class="faux-block">&nbsp; Powered by <a href="https://www.navtheway.com" target="_blank">Navigate the Way️</a></span>

project:
  type: website
  output-dir: docs

format:
  html: 
    page-layout: article
    fontsize: 1.1em
    theme: 
        dark: darkly
        light: flatly
    css: _html/styles.css
    toc: false 
editor: source
