
# Website settings:
website:
  reader-mode: true
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel." 
  # margin-header: html/subscribe.html
  navbar:
    pinned: false
    collapse: true
    logo: img/ocfavicon.jpeg
    # navbar menu
    left:
      - text: "Home"
        href: index.qmd
      - text: "Information"
        menu: 
          - text: "About"
            href: about.qmd
          - text: "Creator"
            href: https://ocardec.github.io 
            target: _blank
      - text: "References"
        href: references/index.qmd
    # social media handles
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:ocmain@gocardec.com"  
      - icon: linkedin
        href: https://www.linkedin.com/in/oscarcardec/
        target: _blank

# ====== Don't touch unless you know what you're doing ======
  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      <span class="faux-block">&nbsp; Powered by <a href="https://www.navtheway.com" target="_blank">NTW ✝️</a></span>
    center: 
      - "&#169; Copyright 2024 Cardec Solutions &nbsp;"
      - icon: twitter 
        href: https://x.com/CardO37474 
        target: _blank 
      - icon: github
        href: https://github.com/ocardec
        target: _blank
    right: |
      <span class="faux-block">Crafted in <a href="https://quarto.org" target="_blank"><img src="img/quarto.png" width="80"></a></span>

project:
  type: website
  output-dir: docs

format:
  html: 
    page-layout: article
    fontsize: 1.1 em
    theme:
      light: flatly
      dark: darkly
    css: html/styles.css
    toc: false

editor: visual
