website:
  reader-mode: true
  title: "The Upside-Down Blog"
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel."
  site-url: https://theupsidedownblog.netlify.app
  favicon: img/usdfavi.png
  google-analytics: "G-V3QQ28RRMM"
  
  navbar:
    pinned: false
    collapse: true
    logo: img/usdfavi.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Information"
        menu: 
          - text: "About"
            href: about.qmd
          - text: "Creator"
            href: https://ocardec.github.io 
            target: _blank
      - text: "References"
        href: references/index.qmd
    right:
      - icon: envelope
        text: Email
        href: "mailto:ocmain@gocardec.com"  
      - icon: rss
        href: index.xml

  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      <span class="faux-block">&nbsp; Powered by <a href="https://www.navtheway.com" target="_blank"><img src="/img/ntw.png" width="30"></a></span>
    center: |
      <span class="faux-block">&#169; Copyright 2024 Cardec Solutions</span>
    right: |
      <span class="faux-block">Crafted in <a href="https://quarto.org" target="_blank"><img src="/img/quarto.png" width="70"></a></span>
      <span class="faux-block">&nbsp; Hosted in <a href="https://www.netlify.com" target="_blank"><img src="/img/netlify.png" width="40"></a></span>
      
project:
  type: website
  output-dir: docs

format:
  html: 
    page-layout: article
    fontsize: 1.1em
    theme: 
        light: flatly
        dark: darkly
    css: html/styles.css
    toc: false
    
editor: visual
