
# Website settings:
website:
  reader-mode: true
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel." #a brief slogan (optional)

  navbar:
    pinned: false
    collapse: true
    logo: img/ocfavicon.jpeg
    
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "References"
        href: references/index.qmd   
        
    # social media handles
    right:
      - icon: twitter
        href: https://twitter.com/CardO37474
      - icon: envelope
        aria-label: email
        href: "mailto:ocmain@gocardec.com"  

# Don't touch unless you know what you're doing :) ========================
  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      <span class="faux-block"> &#169; Cardec Solutions </span>
    center: |
      <span class="faux-block"> <a href="https://www.navtheway.com"> Powered by NTW ✝ </a > </span>
    right: |
      <span class="faux-block"> Aug 2024 </span>

project:
  type: website
  output-dir: docs

format:
  html: 
    page-layout: article
    fontsize: 1.1 em
    theme:
      light: flatly
      dark: darkly
    css: html/styles.css
    toc: false

editor: visual
