
website:
  reader-mode: true
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel."
  favicon: img/usdfavi.png
  google-analytics: "G-V3QQ28RRMM"
  
  navbar:
    pinned: false
    collapse: true
    logo: img/usdfavi.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Information"
        menu: 
          - text: "About"
            href: about.qmd
          - text: "Creator"
            href: https://ocardec.github.io 
            target: _blank
      - text: "References"
        href: references/index.qmd
    right:
      # - icon: rss
      #   href: docs/index.html
      - icon: envelope
        text: Email
        # aria-label: email
        href: "mailto:ocmain@gocardec.com"  

  search: 
    location: navbar
    type: textbox
    
  page-footer:
    # background: 'dark'
    left: |
      <span class="faux-block">&nbsp; Powered by <a href="https://www.navtheway.com" target="_blank">NTW</a></span>
    center: 
      - "&#169; Copyright 2024 Cardec Solutions &nbsp;"
    right: |
      <span class="faux-block">Crafted in <a href="https://quarto.org" target="_blank"><img src="/img/quarto.png" width="70"></a></span>
      
project:
  type: website
  output-dir: docs
format:
  html: 
    page-layout: article
    fontsize: 1.1 em
    theme: 
        light: flatly
        dark: darkly
    css: html/styles.css
    toc: false
    
editor: visual
