website:
  reader-mode: true
  title: ""
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel."
  site-url: https://theupsidedownblog.netlify.app
  favicon: img/tud_logo2.png
  google-analytics: "G-V3QQ28RRMM"
  #margin-footer: html/subscribe.html
  
  navbar:
    pinned: false
    collapse: true
    logo: img/tud_logo2.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Information"
        menu: 
          - text: "About"
            href: about.qmd
          - text: "Creator"
            href: https://ocardec.netlify.app
            target: _blank
      - text: "References"
        href: references/index.qmd
    right:
      - icon: envelope
        text: Email
        href: "mailto:admin@theupsidedownblog.com"  
      # - icon: rss
      #   href: docs/index.xml

  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      <span class="faux-block">&#169; Copyright 2024 Cardec Solutions</span>
    center: |
      <span class="faux-block">Created in <a href="https://quarto.org" target="_blank"> <img src="/img/quarto.png" width="70"></a></span>
    right: |
      <span class="faux-block">&nbsp; Powered by <a href="https://www.navtheway.com" target="_blank">Navigate the Way️</a></span>
      
project:
  # title: "The Upside-Down"
  type: website
  output-dir: docs

format:
  html: 
    title: "Welcome to the Upside-Down Blog!"
    page-layout: article
    fontsize: 1.1em
    theme: 
        light: flatly
        dark: darkly
    css: html/styles.css
    toc: false
    
editor: visual
