
# Website settings:
website:
  reader-mode: true
  description: "Welcome to The Upside-Down blog, a place where paradox and mystery come alive in the light of the Gospel." #a brief slogan (optional)

  # margin-header: html/subscribe.html
  
  navbar:
    pinned: false
    collapse: true
    logo: img/ocfavicon.jpeg
    
    left:
      - text: "Home"
        href: index.qmd
      - text: "Information"
        menu: 
          - text: "About"
            href: about.qmd
          - text: "Creator"
            href: https://ocardec.github.io 
            target: _blank
      - text: "References"
        href: references/index.qmd   
        
    # social media handles
    right:
      - icon: twitter
        href: https://twitter.com/CardO37474
        target: _blank
      - icon: envelope
        aria-label: email
        href: "mailto:ocmain@gocardec.com"  

# Don't touch unless you know what you're doing :) ========================
  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      <span class="faux-block"> &#169; Copyright 2024, Cardec Solutions </span>
    center: |
      <span class="faux-block"> Powered by <a href="https://www.navtheway.com" target="_blank">Navigate The Way</a></span>
    right: |
      <span class="faux-block"> Website made with <a href="https://quarto.org" target="_blank">Quarto</a></span>

project:
  type: website
  output-dir: docs

format:
  html: 
    page-layout: article
    fontsize: 1.1 em
    theme:
      light: flatly
      dark: darkly
    css: html/styles.css
    toc: false

editor: visual
