#_test

title: "Spanish-YAML"
lang: es

website:
  # reader-mode: true
  title: ""
  description: "¡Bienvenidos al blog invertido, un lugar donde la paradoja y el misterio se desarrollan a la luz del Evangelio."
  # site-url: https://theupsidedownblog.netlify.app
  favicon: /images/round_logo2.png
  # google-analytics: "G-V3QQ28RRMM"
  navbar: 
    pinned: false
    collapse: true
    logo: /images/round_logo2.png
    left:
      - text: "Inicio"
        href: index-es.qmd
      - text: "Información"
        menu: 
          - text: "Descripción"
            href: about-es.qmd
          - text: "Autor"
            href: https://ocardec.netlify.app
            target: _blank
      - text: "Referencias"
        href: referencias/referdx-es.qmd
    right:
      - text: "English"
        href: ~/theupsidedown/index.qmd
      - text: "Español"
        href: index-es.qmd
      - icon: envelope-at
        text: Email
        href: "mailto:admin@theupsidedownblog.com"  

params:
  Inicio:
    source: _quarto.yml
  Información:
    source: _quarto.yml
  
    
  search: 
    location: navbar
    type: textbox
    
  page-footer:
    left: |
      <span class="faux-block">&#169; Derechos Reservados 2024 Cardec Solutions</span>
    center: |
      <span class="faux-block">Creado en <a href="https://quarto.org" target="_blank"><img src="/images/quarto.png" width="65"></a></span>
    right: |
      <span class="faux-block">&nbsp; Apoyado por <a href="https://www.navtheway.com" target="_blank">Navigate the Way️</a></span>
  back-to-top-navigation: true
project:
  type: website
  output-dir: ../docs/es

format:
  html: 
    page-layout: article
    fontsize: 1.1em
    theme: 
        dark: darkly
        light: flatly
    css: ../_html/styles.css
    toc: false 
editor: source
